apiVersion: v1
kind: Secret
metadata:
  name: dagster-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/wildcard.localtest.me.pem" | b64enc }}
  tls.key: {{ .Files.Get "certs/wildcard.localtest.me-key.pem" | b64enc }}
