apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dagster-io.github.io/helm
    chart: dagster
    targetRevision: 1.12.1   # or latest
    helm:
      releaseName: dagster
      values: |
        dagsterWebserver:
          service:
            type: ClusterIP
          workspace:
            enabled: false
        postgresql:
          enabled: true
          auth:
            username: dagster
            password: dagster
            database: dagster
          primary:
            persistence:
              enabled: false

        dagster-user-deployments:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
