apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://dagster-io.github.io/helm
    chart: dagster
    targetRevision: 1.12.1
    helm:
      releaseName: dagster
      values: |
        dagsterWebserver:
          service:
            type: ClusterIP
          # Use workspace.yaml + user-code gRPC server
          workspace:
            enabled: true
            servers:
              - host: "dagster-user-deployments-k8s-example-user-code-1"
                port: 3030
                name: "user-code-example"
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: dagster.localtest.me
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - dagster.localtest.me
                secretName: dagster-tls

        postgresql:
          enabled: true
          auth:
            username: dagster
            password: dagster
            database: dagster
          primary:
            persistence:
              enabled: false

        dagster-user-deployments:
          enabled: true
          enableSubchart: true
          deployments:
            - name: "k8s-example-user-code-1"
              image:
                repository: "docker.io/dagster/user-code-example"
                # tag: ~  # let it default to chart version
                pullPolicy: IfNotPresent
              dagsterApiGrpcArgs:
                - "--python-file"
                - "/example_project/example_repo/repo.py"
              port: 3030


  destination:
    server: https://kubernetes.default.svc
    namespace: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
