apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/anandkpai/argocd-platform.git
    targetRevision: main
    path: apps/dagster      
   
    helm:
      releaseName: dagster
      valueFiles:
        - dagster-values.yaml
        - dagster-user-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
